import type { Product } from '@fitcheck/affiliates';

export const OUTERWEAR_IMAGE_KEYS = [
  'p01-trench',
  'p02-leather',
  'p03-denim',
  'p04-camel-coat',
  'p05-puffer',
  'p06-bomber',
  'p37-peacoat',
  'p38-teddy-coat',
  'p39-grey-blazer',
  'p40-raincoat',
  'p41-suede-jacket',
  'p42-wool-overshirt',
] as const;

export const DRESS_IMAGE_KEYS = [
  'p07-slip-dress',
  'p08-knit-midi',
  'p09-floral-wrap',
  'p10-black-mini',
  'p11-linen-shirt',
  'p12-emerald-maxi',
  'p43-black-slip',
  'p44-broderie-sundress',
  'p45-polka-wrap',
  'p46-knit-maxi',
  'p47-sequin-mini',
  'p48-tiered-midi',
] as const;

export const TOP_IMAGE_KEYS = [
  'p13-poplin-shirt',
  'p14-silk-blouse',
  'p15-breton-tee',
  'p16-cashmere-crew',
  'p17-cable-knit',
  'p18-turtleneck',
  'p19-satin-cami',
  'p20-oversized-tee',
  'p21-navy-cardigan',
  'p22-mohair-sweater',
  'p23-chambray-shirt',
  'p24-corset-top',
] as const;

export const BOTTOM_IMAGE_KEYS = [
  'p25-straight-jeans',
  'p26-tailored-trousers',
  'p27-wide-leg',
  'p28-pleated-skirt',
  'p29-leather-skirt',
  'p30-linen-trousers',
  'p31-flared-jeans',
  'p32-cargo-pants',
  'p33-satin-skirt',
  'p34-pencil-skirt',
  'p35-knit-joggers',
  'p36-plaid-mini',
] as const;

export const DEMO_IMAGE_KEYS: readonly string[] = [
  ...OUTERWEAR_IMAGE_KEYS,
  ...DRESS_IMAGE_KEYS,
  ...TOP_IMAGE_KEYS,
  ...BOTTOM_IMAGE_KEYS,
];

/** The 48 hero items with real bundled images. */
export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'fc-owr-001',
    title: 'Sand Belted Trench Coat',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'outerwear',
    priceCents: 8990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/sand-belted-trench-coat_87000101.html',
    imageKey: 'p01-trench',
    commissionPct: 6,
    colors: ['sand'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-002',
    title: 'Black Cropped Leather Jacket',
    brand: 'Sable Row',
    programId: 'asos',
    network: 'awin',
    category: 'outerwear',
    priceCents: 8500,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/black-cropped-leather-jacket/prd/206000102',
    imageKey: 'p02-leather',
    commissionPct: 7,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-003',
    title: 'Oversized Vintage-Wash Denim Jacket',
    brand: 'Arlo & Wren',
    programId: 'shein',
    network: 'awin',
    category: 'outerwear',
    priceCents: 3200,
    currency: 'USD',
    productUrl: 'https://us.shein.com/oversized-vintage-wash-denim-jacket-p-10000103.html',
    imageKey: 'p03-denim',
    commissionPct: 15,
    colors: ['light-wash blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-004',
    title: 'Camel Wool Overcoat',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'outerwear',
    priceCents: 39500,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/camel-wool-overcoat-item-19000104.aspx',
    imageKey: 'p04-camel-coat',
    commissionPct: 10,
    colors: ['camel'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-005',
    title: 'Glossy Black Cropped Puffer',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'outerwear',
    priceCents: 5999,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000105.html',
    imageKey: 'p05-puffer',
    commissionPct: 8,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-006',
    title: 'Olive Satin Bomber Jacket',
    brand: 'Fera',
    programId: 'reformation',
    network: 'cj',
    category: 'outerwear',
    priceCents: 24800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/olive-satin-bomber-jacket',
    imageKey: 'p06-bomber',
    commissionPct: 9,
    colors: ['olive'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-007',
    title: 'Champagne Satin Slip Dress',
    brand: 'Solene',
    programId: 'reformation',
    network: 'cj',
    category: 'dress',
    priceCents: 21800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/champagne-satin-slip-dress',
    imageKey: 'p07-slip-dress',
    commissionPct: 10,
    colors: ['champagne'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-008',
    title: 'Charcoal Ribbed Knit Midi Dress',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'dress',
    priceCents: 4499,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000108.html',
    imageKey: 'p08-knit-midi',
    commissionPct: 7,
    colors: ['charcoal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-009',
    title: 'Red Floral Wrap Midi Dress',
    brand: 'Calla Noir',
    programId: 'asos',
    network: 'awin',
    category: 'dress',
    priceCents: 5200,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/red-floral-wrap-midi-dress/prd/206000109',
    imageKey: 'p09-floral-wrap',
    commissionPct: 6,
    colors: ['red floral'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-010',
    title: 'Structured Black Mini Dress',
    brand: 'Anouk',
    programId: 'shein',
    network: 'awin',
    category: 'dress',
    priceCents: 2450,
    currency: 'USD',
    productUrl: 'https://us.shein.com/structured-black-mini-dress-p-10000110.html',
    imageKey: 'p10-black-mini',
    commissionPct: 18,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-011',
    title: 'White Linen Shirt Dress',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'dress',
    priceCents: 6990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/white-linen-shirt-dress_87000111.html',
    imageKey: 'p11-linen-shirt',
    commissionPct: 5,
    colors: ['white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-012',
    title: 'Emerald Satin Cowl Maxi Dress',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'dress',
    priceCents: 33000,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/emerald-satin-cowl-maxi-dress-item-19000112.aspx',
    imageKey: 'p12-emerald-maxi',
    commissionPct: 11,
    colors: ['emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  // ---------------------------------- tops ----------------------------------
  {
    id: 'fc-top-013',
    title: 'Crisp Poplin Button-Up',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'top',
    priceCents: 3499,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000113.html',
    imageKey: 'p13-poplin-shirt',
    commissionPct: 8,
    colors: ['white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-014',
    title: 'Black Silk Blouse',
    brand: 'Solene',
    programId: 'reformation',
    network: 'cj',
    category: 'top',
    priceCents: 16800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/black-silk-blouse',
    imageKey: 'p14-silk-blouse',
    commissionPct: 10,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-top-015',
    title: 'Striped Breton Tee',
    brand: 'Arlo & Wren',
    programId: 'asos',
    network: 'awin',
    category: 'top',
    priceCents: 2800,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/striped-breton-tee/prd/206000115',
    imageKey: 'p15-breton-tee',
    commissionPct: 6,
    colors: ['navy stripe', 'white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-016',
    title: 'Grey Cashmere Crewneck',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'top',
    priceCents: 29500,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/grey-cashmere-crewneck-item-19000116.aspx',
    imageKey: 'p16-cashmere-crew',
    commissionPct: 11,
    colors: ['grey marl'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-top-017',
    title: 'Cream Cable-Knit Sweater',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'top',
    priceCents: 7990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/cream-cable-knit-sweater_87000117.html',
    imageKey: 'p17-cable-knit',
    commissionPct: 6,
    colors: ['cream'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-018',
    title: 'Fitted Black Turtleneck',
    brand: 'Anouk',
    programId: 'shein',
    network: 'awin',
    category: 'top',
    priceCents: 1900,
    currency: 'USD',
    productUrl: 'https://us.shein.com/fitted-black-turtleneck-p-10000118.html',
    imageKey: 'p18-turtleneck',
    commissionPct: 16,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-top-019',
    title: 'Ivory Satin Camisole',
    brand: 'Calla Noir',
    programId: 'shein',
    network: 'awin',
    category: 'top',
    priceCents: 2200,
    currency: 'USD',
    productUrl: 'https://us.shein.com/ivory-satin-camisole-p-10000119.html',
    imageKey: 'p19-satin-cami',
    commissionPct: 14,
    colors: ['ivory'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-top-020',
    title: 'Oversized Heavyweight Tee',
    brand: 'Sable Row',
    programId: 'asos',
    network: 'awin',
    category: 'top',
    priceCents: 3200,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/oversized-heavyweight-tee/prd/206000120',
    imageKey: 'p20-oversized-tee',
    commissionPct: 7,
    colors: ['washed grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-021',
    title: 'Navy Fine-Knit Cardigan',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'top',
    priceCents: 4999,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000121.html',
    imageKey: 'p21-navy-cardigan',
    commissionPct: 7,
    colors: ['navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-022',
    title: 'Red Mohair Sweater',
    brand: 'Vesper Lane',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'top',
    priceCents: 34000,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/red-mohair-sweater-item-19000122.aspx',
    imageKey: 'p22-mohair-sweater',
    commissionPct: 12,
    colors: ['scarlet'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-top-023',
    title: 'Chambray Shirt',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'top',
    priceCents: 5990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/chambray-shirt_87000123.html',
    imageKey: 'p23-chambray-shirt',
    commissionPct: 5,
    colors: ['chambray blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-top-024',
    title: 'Structured Corset Top',
    brand: 'Fera',
    programId: 'reformation',
    network: 'cj',
    category: 'top',
    priceCents: 15800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/structured-corset-top',
    imageKey: 'p24-corset-top',
    commissionPct: 9,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  // --------------------------------- bottoms --------------------------------
  {
    id: 'fc-btm-025',
    title: 'Straight-Leg Jeans',
    brand: 'Arlo & Wren',
    programId: 'asos',
    network: 'awin',
    category: 'bottom',
    priceCents: 4800,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/straight-leg-jeans/prd/206000125',
    imageKey: 'p25-straight-jeans',
    commissionPct: 6,
    colors: ['mid-wash blue'],
    sizes: ['24', '26', '28', '30', '32'],
    featured: true,
  },
  {
    id: 'fc-btm-026',
    title: 'Black Tailored Trousers',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'bottom',
    priceCents: 6990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/black-tailored-trousers_87000126.html',
    imageKey: 'p26-tailored-trousers',
    commissionPct: 6,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-btm-027',
    title: 'Beige Wide-Leg Trousers',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'bottom',
    priceCents: 4499,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000127.html',
    imageKey: 'p27-wide-leg',
    commissionPct: 8,
    colors: ['beige'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-btm-028',
    title: 'Grey Pleated Midi Skirt',
    brand: 'Vesper Lane',
    programId: 'hm',
    network: 'awin',
    category: 'bottom',
    priceCents: 3999,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000128.html',
    imageKey: 'p28-pleated-skirt',
    commissionPct: 9,
    colors: ['grey'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-btm-029',
    title: 'Leather Midi Skirt',
    brand: 'Sable Row',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'bottom',
    priceCents: 42000,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/leather-midi-skirt-item-19000129.aspx',
    imageKey: 'p29-leather-skirt',
    commissionPct: 10,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-btm-030',
    title: 'White Linen Trousers',
    brand: 'Solene',
    programId: 'reformation',
    network: 'cj',
    category: 'bottom',
    priceCents: 17800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/white-linen-trousers',
    imageKey: 'p30-linen-trousers',
    commissionPct: 11,
    colors: ['white'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-btm-031',
    title: 'Dark-Wash Flared Jeans',
    brand: 'Fera',
    programId: 'reformation',
    network: 'cj',
    category: 'bottom',
    priceCents: 16800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/dark-wash-flared-jeans',
    imageKey: 'p31-flared-jeans',
    commissionPct: 8,
    colors: ['dark indigo'],
    sizes: ['24', '26', '28', '30', '32'],
    featured: true,
  },
  {
    id: 'fc-btm-032',
    title: 'Khaki Cargo Pants',
    brand: 'Anouk',
    programId: 'shein',
    network: 'awin',
    category: 'bottom',
    priceCents: 2800,
    currency: 'USD',
    productUrl: 'https://us.shein.com/khaki-cargo-pants-p-10000132.html',
    imageKey: 'p32-cargo-pants',
    commissionPct: 17,
    colors: ['khaki'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-btm-033',
    title: 'Satin Bias Maxi Skirt',
    brand: 'Calla Noir',
    programId: 'asos',
    network: 'awin',
    category: 'bottom',
    priceCents: 4200,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/satin-bias-maxi-skirt/prd/206000133',
    imageKey: 'p33-satin-skirt',
    commissionPct: 7,
    colors: ['champagne'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-btm-034',
    title: 'Camel Pencil Skirt',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'bottom',
    priceCents: 5990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/camel-pencil-skirt_87000134.html',
    imageKey: 'p34-pencil-skirt',
    commissionPct: 7,
    colors: ['camel'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-btm-035',
    title: 'Cream Knit Joggers',
    brand: 'Arlo & Wren',
    programId: 'shein',
    network: 'awin',
    category: 'bottom',
    priceCents: 2400,
    currency: 'USD',
    productUrl: 'https://us.shein.com/cream-knit-joggers-p-10000135.html',
    imageKey: 'p35-knit-joggers',
    commissionPct: 15,
    colors: ['cream'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-btm-036',
    title: 'Plaid Wool Mini Skirt',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'bottom',
    priceCents: 26500,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/plaid-wool-mini-skirt-item-19000136.aspx',
    imageKey: 'p36-plaid-mini',
    commissionPct: 9,
    colors: ['brown plaid'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  // -------------------------------- outerwear -------------------------------
  {
    id: 'fc-owr-037',
    title: 'Black Wool Peacoat',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'outerwear',
    priceCents: 38500,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/black-wool-peacoat-item-19000137.aspx',
    imageKey: 'p37-peacoat',
    commissionPct: 12,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-038',
    title: 'Cream Teddy Coat',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'outerwear',
    priceCents: 8499,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000138.html',
    imageKey: 'p38-teddy-coat',
    commissionPct: 8,
    colors: ['cream'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-039',
    title: 'Oversized Grey Blazer',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'outerwear',
    priceCents: 8990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/oversized-grey-blazer_87000139.html',
    imageKey: 'p39-grey-blazer',
    commissionPct: 6,
    colors: ['grey'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-040',
    title: 'Navy Longline Raincoat',
    brand: 'Sable Row',
    programId: 'asos',
    network: 'awin',
    category: 'outerwear',
    priceCents: 8500,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/navy-longline-raincoat/prd/206000140',
    imageKey: 'p40-raincoat',
    commissionPct: 7,
    colors: ['navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-041',
    title: 'Brown Suede Trucker Jacket',
    brand: 'Fera',
    programId: 'reformation',
    network: 'cj',
    category: 'outerwear',
    priceCents: 32800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/brown-suede-trucker-jacket',
    imageKey: 'p41-suede-jacket',
    commissionPct: 10,
    colors: ['chocolate brown'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-042',
    title: 'Checked Wool Overshirt',
    brand: 'Arlo & Wren',
    programId: 'shein',
    network: 'awin',
    category: 'outerwear',
    priceCents: 3600,
    currency: 'USD',
    productUrl: 'https://us.shein.com/checked-wool-overshirt-p-10000142.html',
    imageKey: 'p42-wool-overshirt',
    commissionPct: 13,
    colors: ['brown check'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // --------------------------------- dresses --------------------------------
  {
    id: 'fc-drs-043',
    title: 'Black Slip Midi Dress',
    brand: 'Solene',
    programId: 'reformation',
    network: 'cj',
    category: 'dress',
    priceCents: 19800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/black-slip-midi-dress',
    imageKey: 'p43-black-slip',
    commissionPct: 10,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-044',
    title: 'White Broderie Sundress',
    brand: 'Calla Noir',
    programId: 'mango',
    network: 'rakuten',
    category: 'dress',
    priceCents: 7990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/white-broderie-sundress_87000144.html',
    imageKey: 'p44-broderie-sundress',
    commissionPct: 5,
    colors: ['white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-045',
    title: 'Polka-Dot Wrap Dress',
    brand: 'Anouk',
    programId: 'asos',
    network: 'awin',
    category: 'dress',
    priceCents: 5600,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/polka-dot-wrap-dress/prd/206000145',
    imageKey: 'p45-polka-wrap',
    commissionPct: 6,
    colors: ['black polka dot'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-046',
    title: 'Camel Knit Maxi Dress',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'dress',
    priceCents: 5999,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000146.html',
    imageKey: 'p46-knit-maxi',
    commissionPct: 7,
    colors: ['camel'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-047',
    title: 'Silver Sequin Mini Dress',
    brand: 'Vesper Lane',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'dress',
    priceCents: 41000,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/silver-sequin-mini-dress-item-19000147.aspx',
    imageKey: 'p47-sequin-mini',
    commissionPct: 13,
    colors: ['silver'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-048',
    title: 'Sage Tiered Midi Dress',
    brand: 'Anouk',
    programId: 'shein',
    network: 'awin',
    category: 'dress',
    priceCents: 2900,
    currency: 'USD',
    productUrl: 'https://us.shein.com/sage-tiered-midi-dress-p-10000148.html',
    imageKey: 'p48-tiered-midi',
    commissionPct: 16,
    colors: ['sage'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
];
