import type { Product } from '@fitcheck/affiliates';

export const OUTERWEAR_IMAGE_KEYS = [
  'p01-trench',
  'p02-leather',
  'p03-denim',
  'p04-camel-coat',
  'p05-puffer',
  'p06-bomber',
] as const;

export const DRESS_IMAGE_KEYS = [
  'p07-slip-dress',
  'p08-knit-midi',
  'p09-floral-wrap',
  'p10-black-mini',
  'p11-linen-shirt',
  'p12-emerald-maxi',
] as const;

export const DEMO_IMAGE_KEYS: readonly string[] = [...OUTERWEAR_IMAGE_KEYS, ...DRESS_IMAGE_KEYS];

/** The 12 hero items with real bundled images. */
export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'fc-owr-001',
    title: 'Sand Belted Trench Coat',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'outerwear',
    priceCents: 8990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/sand-belted-trench-coat_87000101.html',
    imageKey: 'p01-trench',
    commissionPct: 6,
    colors: ['sand'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-002',
    title: 'Black Cropped Leather Jacket',
    brand: 'Sable Row',
    programId: 'asos',
    network: 'awin',
    category: 'outerwear',
    priceCents: 8500,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/black-cropped-leather-jacket/prd/206000102',
    imageKey: 'p02-leather',
    commissionPct: 7,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-003',
    title: 'Oversized Vintage-Wash Denim Jacket',
    brand: 'Arlo & Wren',
    programId: 'shein',
    network: 'awin',
    category: 'outerwear',
    priceCents: 3200,
    currency: 'USD',
    productUrl: 'https://us.shein.com/oversized-vintage-wash-denim-jacket-p-10000103.html',
    imageKey: 'p03-denim',
    commissionPct: 15,
    colors: ['light-wash blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-004',
    title: 'Camel Wool Overcoat',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'outerwear',
    priceCents: 39500,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/camel-wool-overcoat-item-19000104.aspx',
    imageKey: 'p04-camel-coat',
    commissionPct: 10,
    colors: ['camel'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-owr-005',
    title: 'Glossy Black Cropped Puffer',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'outerwear',
    priceCents: 5999,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000105.html',
    imageKey: 'p05-puffer',
    commissionPct: 8,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-owr-006',
    title: 'Olive Satin Bomber Jacket',
    brand: 'Fera',
    programId: 'reformation',
    network: 'cj',
    category: 'outerwear',
    priceCents: 24800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/olive-satin-bomber-jacket',
    imageKey: 'p06-bomber',
    commissionPct: 9,
    colors: ['olive'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-007',
    title: 'Champagne Satin Slip Dress',
    brand: 'Solene',
    programId: 'reformation',
    network: 'cj',
    category: 'dress',
    priceCents: 21800,
    currency: 'USD',
    productUrl: 'https://www.thereformation.com/products/champagne-satin-slip-dress',
    imageKey: 'p07-slip-dress',
    commissionPct: 10,
    colors: ['champagne'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-008',
    title: 'Charcoal Ribbed Knit Midi Dress',
    brand: 'Ode Studio',
    programId: 'hm',
    network: 'awin',
    category: 'dress',
    priceCents: 4499,
    currency: 'USD',
    productUrl: 'https://www2.hm.com/en_us/productpage.1200000108.html',
    imageKey: 'p08-knit-midi',
    commissionPct: 7,
    colors: ['charcoal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-009',
    title: 'Red Floral Wrap Midi Dress',
    brand: 'Calla Noir',
    programId: 'asos',
    network: 'awin',
    category: 'dress',
    priceCents: 5200,
    currency: 'USD',
    productUrl: 'https://www.asos.com/us/fitcheck/red-floral-wrap-midi-dress/prd/206000109',
    imageKey: 'p09-floral-wrap',
    commissionPct: 6,
    colors: ['red floral'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-010',
    title: 'Structured Black Mini Dress',
    brand: 'Anouk',
    programId: 'shein',
    network: 'awin',
    category: 'dress',
    priceCents: 2450,
    currency: 'USD',
    productUrl: 'https://us.shein.com/structured-black-mini-dress-p-10000110.html',
    imageKey: 'p10-black-mini',
    commissionPct: 18,
    colors: ['black'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
  {
    id: 'fc-drs-011',
    title: 'White Linen Shirt Dress',
    brand: 'Maren',
    programId: 'mango',
    network: 'rakuten',
    category: 'dress',
    priceCents: 6990,
    currency: 'USD',
    productUrl: 'https://shop.mango.com/us/women/white-linen-shirt-dress_87000111.html',
    imageKey: 'p11-linen-shirt',
    commissionPct: 5,
    colors: ['white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: 'fc-drs-012',
    title: 'Emerald Satin Cowl Maxi Dress',
    brand: 'Lumen Atelier',
    programId: 'farfetch',
    network: 'partnerize',
    category: 'dress',
    priceCents: 33000,
    currency: 'USD',
    productUrl: 'https://www.farfetch.com/shopping/women/emerald-satin-cowl-maxi-dress-item-19000112.aspx',
    imageKey: 'p12-emerald-maxi',
    commissionPct: 11,
    colors: ['emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
  },
];
